# Generated by Django 5.2.5 on 2025-10-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor'), ('Medicinal', 'Medicinal'), ('Flowering', 'Flowering')], max_length=50)),
                ('price', models.IntegerField()),
                ('about', models.TextField(blank=True, help_text='Write details about the plant', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('discount_percent', models.IntegerField(default=0)),
            ],
        ),
    ]
