# Generated by Django 5.2.5 on 2025-10-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='discount_percent',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='price',
            field=models.FloatField(),
        ),
    ]
