# Generated by Django 5.2.5 on 2025-10-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_plant_about_alter_plant_discount_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='about',
            field=models.TextField(),
        ),
    ]
